include:
  - board: seeeduino_xiao_ble
    shield: Enigma_01 rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DKEYMAP_FILE=../../config/Enigma_01_a.keymap
    artifact-name: Enigma_01 layout_a
    
  - board: seeeduino_xiao_ble
    shield: Enigma_01 rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DKEYMAP_FILE=../../config/Enigma_01_b.keymap
    artifact-name: Enigma_01 layout_b
    
  - board: seeeduino_xiao_ble
    shield: Enigma_01 rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DKEYMAP_FILE=../../config/Enigma_01_c.keymap
    artifact-name: Enigma_01 layout_c

  - board: seeeduino_xiao_ble
    shield: settings_reset
